name: Run Tests

on:
  pull_request:
    branches:
      - main # or your default branch name

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x] # or whatever Node version you're using

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup caching for node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:remote
        id: tests
        continue-on-error: false

      - name: Set result
        id: result
        run: |
          if [[ "${{ steps.tests.outcome }}" == "success" ]]; then
            echo "::set-output name=grade::A"
            echo "::set-output name=state::passed"
          else
            echo "::set-output name=grade::F"
            echo "::set-output name=state::failed"
          fi
